---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: soarcast-image-update
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: development
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: development
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: soarcast
  update:
    path: ./kubernetes/manifests
    strategy: Setters
